### ISSUE TITLE
stuff due for launch

### ISSUE THREAD

**Issue by irisli** [stellar/stories#20]
- [x] correctly sized viewport color
- [x] non-scaled slides (so images can be 1:1 pixel ratio rendered)
- [x] nav button color (on dark backgrounds)  `background: rgba(255,255,255, 0.8)`
- [x] last slide html
- [x] bottom spacing
- [x] update to new slide images
- [x] preload images so there's no weird flash
- [x] firefox nav bar broken
- [x] share page flexbox prefixing (broken)
- [x] share pane add padding
- [x] fix facebook og:image (#23)
- [x] remove prefixing analytics
- [x] Hash handler on load https://github.com/stellar/stories/issues/18
- [x] Analytics start on focus
- [x] make sure url is correct on share page
- [x] fix viewport sizing (for constrained by width)
- [x] link to summary (add to homepage)

---

Tabled items:
- moved to https://github.com/stellar/stories/issues/15

Added by @bartekn:
- [x] Update OG tags #23 (sorry duplicate)
- [x] Button and link in the last slide does not work
- [x] Can't close share box in mobile chrome

Dependent on others
- [x] upload final graphic novel
- [x] update landing page copy w jessica
